from fork_env.settings import PROJECT_ROOT


SUM_HASH_RATE = 1 / 600
LOG_NORMAL_SIGMA = 1.11
LOMAX_C = 1.3
N_MINER = 19

DATA_FOLDER = PROJECT_ROOT / "data"
FIGURES_FOLDER = PROJECT_ROOT / "figures"

BITCOIN_MINER_PATH = DATA_FOLDER / "bitcoin_miner.pkl"
BITCOIN_MINER_JSON_PATH = DATA_FOLDER / "bitcoin_miner.json"
CLUSTER_PATH = DATA_FOLDER / "clusters.pkl"
